config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get '/profile', to: 'pages#profile'
  patch '/bookings/:id/accept', to: 'bookings#accept', as: :accept
  patch '/bookings/:id/reject', to: 'bookings#reject', as: :reject

  resources :clowns do
    resources :bookings, except: [ :index, :show, :destroy ]
  end
  resources :bookings, only: [ :index, :show, :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :clown

  validates :start_date, :end_date, presence: true

  def accept!
    self.accepted = true
  end

  def reject!
    self.accepted = false
  end
end

app/models/clown.rb
class Clown < ApplicationRecord
  belongs_to :user
  has_many :bookings

  has_one_attached :photo
  # validates :name, :years_of_experience, :gender, :price presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :clowns
  has_many :bookings
  has_one_attached :photo

  # validates :first_name, :last_name, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_clown_id_and_user_id, except: [ :index, :show, :destroy, :accept, :reject]
  before_action :set_booking, only: [ :show, :destroy, :edit, :update, :accept, :reject ]

  def index
    # TODO: Implement logic to accept or deny a booking
    # If the user is the owner of the Mime, SHOW option to accept a booking
    # if the user is not the owner of the Mime, SHOW status of Accepted or not.
    # @bookings = Booking.all
    # @bookings = Booking.where(clown: @clown)
    # @bookings = Booking.where(user_id: current_user)
    @user = current_user
    @clowns = @user.clowns
    @bookings = @user.bookings
  end

  def new
    @booking = Booking.new
  end

  def create
    # TO ASK: Set_params is un
    @booking = Booking.new(set_params)
    @booking.user = @user
    @booking.clown = @clown
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @booking.update(set_params)
      redirect_to booking_path(@booking)
    else
      render :edit
    end
  end

  def destroy
    @booking.destroy
    redirect_to clowns_path
  end

  def accept
    @booking.accept!
    @booking.save
    redirect_to profile_path
  end

  def reject
    @booking.reject!
    @booking.save
    redirect_to profile_path
  end

  private

  def set_clown_id_and_user_id
    @clown = Clown.find(params[:clown_id])
    @user = current_user
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/clowns_controller.rb
class ClownsController < ApplicationController
  def index
    @clowns = Clown.all
  end

  def show
    @clown = Clown.find(params[:id])
  end

  def new
    @clown = Clown.new
  end

  def create
    @clown = Clown.new(clown_params)
    @clown.user = current_user

    if @clown.save
      redirect_to clown_path(@clown), notice: 'Mime was successfully created.'
    else
      render :new
    end
  end

  def edit
    @clown = Clown.find(params[:id])
  end

  def update
    @clown = Clown.find(params[:id])
    if @clown.update(clown_params)
      redirect_to @clown, notice: 'Mime was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @clown = Clown.find(params[:id])
    @clown.destroy
    redirect_to clowns_path
  end

  private

  def clown_params
    params.require(:clown).permit(:name, :years_of_experience, :price, :description, :image_url, :photo)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end

  def profile
    @clowns = current_user.clowns
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<h1>Edit Your Booking</h1>
<div>
  <div class="booking-form">
    <%= simple_form_for [ @clown, @booking ] do |f| %>
      <%= f.input :start_date %>
      <%= f.input :end_date %>
      <%= f.submit "Update", class: "btn btn-danger" %>
    <% end %>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="container bookings-listings">
  <h1>All Bookings</h1>
  <% if @bookings.empty? %>
    You don't have any bookings.
  <% else %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Booking Start date</th>
          <th scope="col">Booking End date</th>
          <th scope="col">Status</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <% @bookings.each do |booking| %>
            <tr>
              <td><%= booking.clown.name %></td>
              <td><%= booking.start_date %></td>
              <td><%= booking.end_date %></td>
              <% if booking.accepted.nil? %>
                <td>Pending</td>
              <% elsif booking.accepted %>
                <td>Accepted</td>
              <% else %>
                <td>Rejected</td>
              <% end %>
            </tr>
          <% end %>
        </tr>
      </tbody>
    </table>
  <% end %>
</div>

app/views/bookings/new.html.erb
<h1>Book <%= @clown.name %></h1>

<div class="booking-form">
  <%= simple_form_for [ @clown, @booking ] do |f| %>
    <%= f.input :start_date %>
    <%= f.input :end_date %>
    <%= f.submit "Book", class: "btn btn-danger" %>
  <% end %>
</div>

app/views/bookings/show.html.erb
<div class="booking-form">
  <h1>Your Booking with <%= @booking.clown.name %></h1>
  <p>Mime's name: <%= @booking.clown.name %></p>
  <p>Start Date: <%= @booking.start_date %></p>
  <p>End Date: <%= @booking.end_date %></p>
  <%= link_to "Back to Home", root_path, class: "btn btn-danger" %>
  <%= link_to "Edit", edit_clown_booking_path(@booking.clown, @booking), class: "btn btn-outline-danger" %>
  <%= link_to "Cancel Booking for #{@booking.clown.name}", booking_path(@booking), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
</div>

app/views/clowns/edit.html.erb
<div class="booking-form">
  <%= simple_form_for(@clown) do |f| %>
    <h1>Edit <%= @clown.name %>'s Listing</h1>

    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :years_of_experience %>
      <%= f.input :description %>
      <%= f.input :price %>
      <%= f.input :photo, as: :file %>
      <div class="form-actions">
        <%= f.button :submit, "Update", class: 'btn btn-danger btn-sm mt-2 mr-1' %>
      </div>
    </div>
  <% end %>
</div>

app/views/clowns/index.html.erb
<div class="container py-5 my-3">
  <div class="d-flex align-items-center justify-content-between mb-3">
    <h3 class="mb-0">Browse through the mimes</h3>
    <%= link_to 'Add a mime', new_clown_path, class: 'btn btn-flat' %>
  </div>

  <div class="cards-mimes">
    <% @clowns.each do |clown| %>
        <%= link_to clown_path(clown), class:'text-decoration-none btn btn-danger' do %>
           <% if clown.photo.attached? %>
            <%= cl_image_tag clown.photo.key, height: 300, width: 317, crop: :fill %>
           <% else %>
            <%= image_tag(clown.image_url, class: "card-mime-image") %>
           <% end %>
            <h3><%= clown.name %></h3>
        <% end %>
    <% end %>
  </div>
</div>

app/views/clowns/new.html.erb
<div class="booking-form">
  <h1>List a New Mime</h1>
  <%= simple_form_for(@clown) do |f| %>
    <%= f.input :name %>
    <%= f.input :years_of_experience %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :photo, as: :file %>
    <div>
      <%= f.button :submit, "Add a mime", class: 'btn btn-danger btn-sm mt-2 mr-1' %>
    </div>
  <% end %>
</div>

app/views/clowns/show.html.erb
<div class="container d-flex mt-3 mb-3">
  <div class="container d-flex flex-column justify-content-start">

    <div class="mime-name-header">
      <h2><%= @clown.name %></h2>
    </div>

    <div class='container p-0 mt-4'>
      <p class='subheader-section'>Details</p>
      <ul class='details-list'>
        <li class='d-flex align-items-center mb-3'>
          <i class="fas fa-dollar-sign mr-2 ml-1"></i>
          <%= @clown.price %> per hour
        </li>
        <li class='d-flex align-items-center'>
          <i class="fas fa-calendar-check mr-2"></i>
          <%= @clown.years_of_experience %>  years of experience
        </li>
      </ul>
    <p class='description-blurb-mime'><%= @clown.description %></p>
    </div>


    <div class="d-flex justify-content-between">
      <%= link_to new_clown_booking_path(@clown) do %>
        <button type="button" class="btn btn-danger">Booking Request</button>
      <% end %>
      <div class="d-flex align-items-center">
        <% if current_user == @clown.user %>
          <p><%= link_to 'Edit', edit_clown_path, class: "btn btn-outline-danger btn-sm mr-2" %></p>
          <p><%= link_to 'Delete', clown_path, method: :delete, data: { confirm: 'are you sure?' }, class: "btn btn-outline-danger btn-sm" %></p>
        <% end %>
      </div>
    </div>
  </div>

  <div class='perspective'>
    <div class='image-mime'>
      <% if @clown.photo.attached? %>
        <%= cl_image_tag @clown.photo.key, :width=>350, :height=>350, :gravity=>"faces", :crop=>"fill" %>
      <% else %>
        <%= image_tag(@clown.image_url, class: 'image-seed-file') %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-mymime">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://cdn.dribbble.com/users/1055435/screenshots/3371597/mime-final.gif" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to "Mimes for Hire", "#", class: "nav-link" %>
        </li>
      <li class="nav-item active">
        <%= link_to "Experiences", "#", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "User123", "#", class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <%= image_tag "https://www.seekpng.com/png/detail/41-410093_circled-user-icon-user-profile-icon-png.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "View Profile", "#", class: "dropdown-item" %>
          <%= link_to "View Bookings", "#", class: "dropdown-item" %>
          <%= link_to "Help", "#", class: "dropdown-item" %>
          <%= link_to "FAQ", "#", class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mymime</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'components/navbar' %>
    <%= yield %>
    <%= render 'components/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0, 0, 0, 0.527),rgba(0, 0, 0, 0.5)), url(https://wallpaperaccess.com/full/6113900.jpg)">
  <div class="banner-content-h1">
    <h1>sublime mimes for memorable times.</h1>
  </div>
  <div class="banner-content-p">
    <p>choosing the right mime isn't always black and white.  with our diverse collection of qualified mimes, you're sure to find a unique mime that's earned their stripes.  </p>
  </div>
    <%= link_to "book a mime", clowns_path, class: "btn btn-danger btn-lg banner-button" %>
</div>

<section>
  <div class="container py-5">

    <h1>In the Spotlight</h1>

    <div class="row no-gutters">
      <div class="col-12 col-lg-6">
        <div class="flipper flipper-xl">
          <div class="flipper-card">
            <div class="flipper-front" style="background-image: url(https://cdn43.picsart.com/168095202002202.jpeg?type=webp&to=min&r=640)"></div>
            <%# <div class="flipper-back">Back</div> %>
          </div>
        </div>
      </div>

      <div class="col-12 col-lg-6">
        <div class="row no-gutters">
          <div class="col-12 col-sm-6">
            <div class="flipper">
              <div class="flipper-card">
                <div class="flipper-front" style="background-image:  url(https://thumbs.gfycat.com/ClearcutAgileHarlequinbug-max-1mb.gif)"></div>
                <%# <div class="flipper-back">Back</div> %>
              </div>
            </div>
          </div>

          <div class="col-12 col-sm-6">
            <div class="flipper">
              <div class="flipper-card">
                <div class="flipper-front" style="background-image: url(https://i.pinimg.com/236x/20/11/8f/20118feafe0883f05557601e9c5d6bc0--creepy-circus-circus-clown.jpg)"></div>
                <%# <div class="flipper-back">Back</div> %>
              </div>
            </div>
          </div>

          <div class="col-12 col-sm-6">
            <div class="flipper">
              <div class="flipper-card flipper-is-flipped">
                <div class="flipper-front">Front</div>
                <div class="flipper-back" style="background-image: url(https://i.pinimg.com/originals/a1/12/6c/a1126c546e2084480b97a3a33529c572.jpg)"></div>
              </div>
            </div>
          </div>

          <div class="col-12 col-sm-6">
            <div class="flipper">
              <div class="flipper-card">
                <div class="flipper-front" style="background-image: url(https://i.pinimg.com/originals/a1/12/6c/a1126c546e2084480b97a3a33529c572.jpg)"></div>
                <%# <div class="flipper-back">Back</div> %>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="col-12 col-sm-6 col-lg-3">
        <div class="flipper">
          <div class="flipper-card">
            <div class="flipper-front" style="background-image: url(https://i.pinimg.com/236x/d2/1a/52/d21a5272342c2c5fdfbc2b5f2a1acd9d--mime-makeup-night-circus.jpg)"></div>
            <%# <div class="flipper-back">Back</div> %>
          </div>
        </div>
      </div>

      <div class="col-12 col-sm-6 col-lg-3">
        <div class="flipper">
          <div class="flipper-card flipper-is-flipped">
            <div class="flipper-front">Front</div>
            <div class="flipper-back" style="background-image: url(https://i.pinimg.com/236x/10/6c/74/106c74e214333c16cd705a977046a518--mime-costume-costume-makeup.jpg)"></div>
          </div>
        </div>
      </div>

      <div class="col-12 col-lg-6">
        <div class="flipper ratio-not-1-1">
          <div class="flipper-card">
            <div class="flipper-front" style="background-image: url(https://64.media.tumblr.com/tumblr_m0nhsakCIA1qfmhbw.gif)"></div>
            <%# <div class="flipper-back">Back</div> %>
          </div>
        </div>
      </div>

      <div class="col-12 col-lg-6">
      </div>
    </div>
  </div>
</section>

app/views/pages/profile.html.erb
<div class="container bookings-listings">
  <h1>MyMime Booking Listing</h1>
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Booking Start date</th>
        <th scope="col">Booking End date</th>
        <th scope="col">Status</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <% @clowns.each do |clown| %>
          <% clown.bookings.each do |booking| %>
            <tr>
              <td><%= link_to clown.name, clown_path(clown), class: 'text-decoration-none link-to' %></td>
              <td><%= booking.start_date.strftime("%b %e, %l:%M %p") %></td>
              <td><%= booking.end_date.strftime("%b %e, %l:%M %p") %></td>

              <td>
                <div class="dropdown show">
                  <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <% if booking.accepted.nil? %>
                      Pending
                    <% elsif booking.accepted %>
                      Accepted
                    <% else %>
                      Rejected
                    <% end %>
                  </a>

                  <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                    <% if booking.accepted.nil? %>
                      <%= link_to 'Accept', accept_path(booking), method: :patch,  class: "dropdown-item" %>
                      <%= link_to 'Reject', reject_path(booking), method: :patch,  class: "dropdown-item" %>
                    <% elsif booking.accepted %>
                      <%= link_to 'Reject', reject_path(booking), method: :patch,  class: "dropdown-item" %>
                    <% else %>
                      <%= link_to 'Accept', accept_path(booking), method: :patch,  class: "dropdown-item" %>
                    <% end %>
                  </div>
                </div>
              </td>
            </tr>
            </td>
          <% end %>
        <% end %>
      </tr>
    </tbody>
  </table>

</div>